Repository eProsima/DDS-Router, pull requests merged in 2021-12, with the labels that each got.

#88 Improving user experience
  include/ddsrouter/types/Log.hpp
  src/cpp/main.cpp
Labels: first-to-merge

#84 Improve error handling in CLI
  src/cpp/user_interface/arguments_configuration.cpp
Labels: first-to-merge

#83 Add examples resources to install
  CMakeLists.txt
Labels: first-to-merge

#81 User interface documentation [13243]
  docs/index.rst
  docs/rst/developer_manual/installation/configuration/cmake_options.rst
  docs/rst/exports/alias.include
  docs/rst/spelling_wordlist.txt
  docs/rst/user_manual/user_interface.rst
  src/cpp/user_interface/arguments_configuration.cpp
Labels: documentation, first-to-merge

#89 Fix History erasing all changes error
  include/ddsrouter/communication/PayloadPool.hpp
  src/cpp/communication/CopyPayloadPool.cpp
  src/cpp/communication/PayloadPool.cpp
  src/cpp/writer/implementations/rtps/Writer.cpp
Labels: first-to-merge

#86 Fix PeriodicHandler error
  include/ddsrouter/event/EventHandler.hpp
  include/ddsrouter/event/FileWatcherHandler.hpp
  include/ddsrouter/event/PeriodicEventHandler.hpp
  include/ddsrouter/event/SignalHandler.hpp
  include/ddsrouter/event/impl/EventHandler.ipp
  include/ddsrouter/event/impl/SignalHandler.ipp
  src/cpp/core/DDSRouter.cpp
  src/cpp/event/FileWatcherHandler.cpp
  src/cpp/event/PeriodicEventHandler.cpp
  src/cpp/main.cpp
Labels: first-to-merge

#94 Add condition variable header
  include/ddsrouter/event/EventHandler.hpp
Labels: first-to-merge

#87 Windows installation from sources documentation
  docs/index.rst
  docs/rst/developer_manual/installation/sources/linux.rst
  docs/rst/developer_manual/installation/sources/windows.rst
  docs/rst/installation/linux.rst
  docs/rst/installation/windows.rst
  docs/rst/spelling_wordlist.txt
Labels: documentation, first-to-merge

#92 Change milliseconds for seconds
  docs/rst/user_manual/user_interface.rst
  src/cpp/user_interface/arguments_configuration.cpp
Labels: first-to-merge

#96 Fail if DDSRouter has not more than 1 participant
  include/ddsrouter/participant/ParticipantsDatabase.hpp
  src/cpp/core/DDSRouter.cpp
  src/cpp/participant/ParticipantsDatabase.cpp
  test/blackbox/implementations/CMakeLists.txt
  test/blackbox/implementations/ImplementationsTest.cpp
  test/unittest/participant/participants_database/CMakeLists.txt
  test/unittest/participant/participants_database/ParticipantsDatabaseTest.cpp
Labels: first-to-merge

#91 Release notes
  docs/rst/exports/alias.include
  docs/rst/notes/notes.rst
  docs/rst/spelling_wordlist.txt
Labels: documentation

#95 Add executable test
  test/CMakeLists.txt
  test/system/CMakeLists.txt
  test/system/executable/CMakeLists.txt
  test/system/executable/configurations/simple_configuration.yaml
  test/system/executable/configurations/void_configuration.yaml
  test/system/executable/launcher.ps1
  test/system/executable/tests.py
Labels: first-to-merge

#102 Fix error handling when participant creation fails
  include/ddsrouter/configuration/DDSRouterConfiguration.hpp
  include/ddsrouter/core/DDSRouter.hpp
  src/cpp/configuration/DDSRouterConfiguration.cpp
  src/cpp/configuration/DiscoveryServerParticipantConfiguration.cpp
Labels: first-to-merge

#101 Add Vulcanexus Cloud use case
  docs/index.rst
  docs/resources/use_cases/vulcanexus_cloud/ConfigMap.yaml
  docs/resources/use_cases/vulcanexus_cloud/Dockerfile_LAN
  docs/resources/use_cases/vulcanexus_cloud/Dockerfile_cloud
  docs/resources/use_cases/vulcanexus_cloud/ddsrouter.yaml
  docs/resources/use_cases/vulcanexus_cloud/listener.yaml
  docs/resources/use_cases/vulcanexus_cloud/load-balancer-service.yaml
  docs/resources/use_cases/vulcanexus_cloud/local-ddsrouter.yaml
  docs/resources/use_cases/vulcanexus_cloud/local-service.yaml
  docs/resources/use_cases/vulcanexus_cloud/run.bash
  docs/rst/exports/alias.include
  docs/rst/figures/vulcanexus_cloud.png
  docs/rst/figures/vulcanexus_k8s.png
  docs/rst/figures/vulcanexus_local.png
  docs/rst/formalia/titlepage.rst
  docs/rst/spelling_wordlist.txt
  docs/rst/use_cases/vulcanexus_cloud.rst
Labels: documentation, first-to-merge
