Repository eProsima/DDS-Router, pull requests merged in 2022-01, with the labels that each got.

#115 Add ROS 2 & Kubernetes use case [13412]
  docs/index.rst
  docs/resources/use_cases/ros_cloud/ConfigMap.yaml
  docs/resources/use_cases/ros_cloud/Dockerfile_ddsrouter
  docs/resources/use_cases/ros_cloud/Dockerfile_listener
  docs/resources/use_cases/ros_cloud/ddsrouter.yaml
  docs/resources/use_cases/ros_cloud/listener.yaml
  docs/resources/use_cases/ros_cloud/load-balancer-service.yaml
  docs/resources/use_cases/ros_cloud/local-ddsrouter.yaml
  docs/resources/use_cases/ros_cloud/local-service.yaml
  docs/resources/use_cases/ros_cloud/run.bash
  docs/resources/use_cases/vulcanexus_cloud/ConfigMap.yaml
  docs/resources/use_cases/vulcanexus_cloud/Dockerfile_cloud
  docs/resources/use_cases/vulcanexus_cloud/local-ddsrouter.yaml
  docs/rst/figures/k8s_cloud_router.png
  docs/rst/figures/k8s_diagram.png
  docs/rst/figures/k8s_local_router.png
  docs/rst/formalia/titlepage.rst
  docs/rst/use_cases/ros_cloud.rst
  docs/rst/user_manual/wan_configuration.rst
Labels: documentation, first-to-merge

#106 Add usage example to getting started [13416]
  docs/index.rst
  docs/resources/getting_started/client-ddsrouter.yaml
  docs/resources/getting_started/server-ddsrouter.yaml
  docs/rst/figures/shapesdemo_circle.png
  docs/rst/figures/shapesdemo_detailed.png
  docs/rst/figures/shapesdemo_general.png
  docs/rst/figures/shapesdemo_publisher.png
  docs/rst/figures/shapesdemo_square.png
  docs/rst/figures/shapesdemo_subscriber.png
  docs/rst/formalia/titlepage.rst
  docs/rst/getting_started/project_overview.rst
  docs/rst/getting_started/usage_example.rst
  docs/rst/spelling_wordlist.txt
Labels: documentation, first-to-merge

#116 Reformat YAML [13423]
  docs/resources/examples/change_domain.yaml
  docs/resources/examples/echo.yaml
  docs/resources/examples/ros_discovery_client.yaml
  docs/resources/examples/ros_discovery_server.yaml
  docs/resources/examples/wan_client.yaml
  docs/resources/examples/wan_server.yaml
  docs/resources/getting_started/client-ddsrouter.yaml
  docs/resources/getting_started/server-ddsrouter.yaml
  docs/rst/examples/ros_discovery_server_example.rst
  docs/rst/examples/wan_example.rst
  docs/rst/getting_started/usage_example.rst
  docs/rst/user_manual/configuration.rst
  docs/rst/user_manual/participants/echo.rst
  docs/rst/user_manual/participants/local_discovery_server.rst
  docs/rst/user_manual/participants/participant.rst
  docs/rst/user_manual/participants/simple.rst
  docs/rst/user_manual/participants/wan.rst
  docs/rst/user_manual/wan_configuration.rst
  resources/configurations/basic_configuration.yaml
  resources/configurations/descriptions/fields/address.yaml
  resources/configurations/descriptions/fields/connection-addresses.yaml
  resources/configurations/descriptions/fields/listening_addresses.yaml
  resources/configurations/example_configuration.yaml
  resources/configurations/examples/change_domain.yaml
  resources/configurations/examples/echo.yaml
  resources/configurations/examples/ros_discovery_client.yaml
  resources/configurations/examples/ros_discovery_server.yaml
  resources/configurations/examples/wan_client.yaml
  resources/configurations/examples/wan_server.yaml
  test/blackbox/ddsrouter_core/resources/dds_test_simple_configuration.yaml
  test/blackbox/ddsrouter_core/resources/trivial_test_dummy_configuration.yaml
Labels: first-to-merge

#113 DNS support [13406]
  docs/rst/user_manual/configuration.rst
  include/ddsrouter/exceptions/ValueNotAllowedException.hpp
  include/ddsrouter/participant/implementations/rtps/impl/DiscoveryServerParticipant.ipp
  include/ddsrouter/types/address/Address.hpp
  include/ddsrouter/types/configuration_tags.hpp
  include/ddsrouter/types/utils.hpp
  resources/configurations/descriptions/fields/address.yaml
  resources/configurations/examples/ros_discovery_client.yaml
  resources/configurations/examples/ros_discovery_server.yaml
  src/cpp/configuration/DDSRouterConfiguration.cpp
  src/cpp/configuration/implementations/Address_configuration.cpp
  src/cpp/types/address/Address.cpp
  src/cpp/types/utils.cpp
  test/unittest/configuration/AddressConfigurationTest.cpp
  test/unittest/configuration/CMakeLists.txt
  test/unittest/participant/participants_database/CMakeLists.txt
  test/unittest/types/participant/CMakeLists.txt
  test/unittest/types/topic/CMakeLists.txt
  test/unittest/types/utils/CMakeLists.txt
Labels: first-to-merge

#118 Add TLS support [13508]
  CMakeLists.txt
  docs/rst/examples/change_domain_example.rst
  docs/rst/examples/echo_example.rst
  docs/rst/examples/ros_discovery_server_example.rst
  docs/rst/examples/wan_example.rst
  docs/rst/spelling_wordlist.txt
  docs/rst/user_manual/participants/participant.rst
  docs/rst/user_manual/wan_configuration.rst
  include/ddsrouter/configuration/DiscoveryServerParticipantConfiguration.hpp
  include/ddsrouter/participant/implementations/rtps/DiscoveryServerParticipant.hpp
  include/ddsrouter/participant/implementations/rtps/impl/DiscoveryServerParticipant.ipp
  include/ddsrouter/types/configuration_tags.hpp
  resources/configurations/security/ca.cnf
  resources/configurations/security/ca.crt
  resources/configurations/security/ca.key
  resources/configurations/security/ca.srl
  resources/configurations/security/commands.md
  resources/configurations/security/ddsrouter.cnf
  resources/configurations/security/ddsrouter.crt
  resources/configurations/security/ddsrouter.csr
  resources/configurations/security/ddsrouter.key
  resources/configurations/security/dh_params.pem
  src/cpp/configuration/DiscoveryServerParticipantConfiguration.cpp
Labels: first-to-merge

#123 Change ParticipantType for ParticipantKind [13544]
  docs/resources/getting_started/client-ddsrouter.yaml
  docs/resources/getting_started/server-ddsrouter.yaml
  docs/resources/use_cases/ros_cloud/ConfigMap.yaml
  docs/resources/use_cases/ros_cloud/local-ddsrouter.yaml
  docs/rst/examples/change_domain_example.rst
  docs/rst/examples/echo_example.rst
  docs/rst/examples/ros_discovery_server_example.rst
  docs/rst/examples/wan_example.rst
  docs/rst/getting_started/project_overview.rst
  docs/rst/user_manual/configuration.rst
  docs/rst/user_manual/participants/echo.rst
  docs/rst/user_manual/participants/local_discovery_server.rst
  docs/rst/user_manual/participants/participant.rst
  docs/rst/user_manual/participants/simple.rst
  docs/rst/user_manual/participants/wan.rst
  docs/rst/user_manual/user_manual_glossary.rst
  docs/rst/user_manual/wan_configuration.rst
  include/ddsrouter/configuration/BaseConfiguration.hpp
  include/ddsrouter/configuration/DDSRouterConfiguration.hpp
  include/ddsrouter/configuration/ParticipantConfiguration.hpp
  include/ddsrouter/core/DDSRouter.hpp
  include/ddsrouter/participant/IParticipant.hpp
  include/ddsrouter/participant/ParticipantFactory.hpp
  include/ddsrouter/participant/implementations/auxiliar/BaseParticipant.hpp
  include/ddsrouter/participant/implementations/auxiliar/VoidParticipant.hpp
  include/ddsrouter/participant/implementations/auxiliar/impl/BaseParticipant.ipp
  include/ddsrouter/participant/implementations/rtps/impl/CommonRTPSRouterParticipant.ipp
  include/ddsrouter/types/configuration_tags.hpp
  include/ddsrouter/types/participant/ParticipantKind.hpp
  include/ddsrouter/types/participant/ParticipantType.hpp
  resources/configurations/descriptions/participants/echo_participant.yaml
  resources/configurations/descriptions/participants/local_discovery_server.yaml
  resources/configurations/descriptions/participants/simple_participant.yaml
  resources/configurations/examples/change_domain.yaml
  resources/configurations/examples/echo.yaml
  resources/configurations/examples/ros_discovery_client.yaml
  resources/configurations/examples/ros_discovery_server.yaml
  resources/configurations/examples/wan_client.yaml
  resources/configurations/examples/wan_server.yaml
  src/cpp/configuration/ParticipantConfiguration.cpp
  src/cpp/core/DDSRouter.cpp
  src/cpp/participant/ParticipantFactory.cpp
  src/cpp/participant/implementations/auxiliar/DummyParticipant.cpp
  src/cpp/participant/implementations/auxiliar/EchoParticipant.cpp
  src/cpp/participant/implementations/auxiliar/VoidParticipant.cpp
  src/cpp/types/participant/ParticipantKind.cpp
  src/cpp/types/participant/ParticipantType.cpp
  test/blackbox/ddsrouter_core/resources/dds_test_simple_configuration.yaml
  test/blackbox/ddsrouter_core/resources/trivial_test_dummy_configuration.yaml
  test/blackbox/ddsrouter_core/resources/trivial_test_void_configuration.yaml
  test/blackbox/implementations/ImplementationsTest.cpp
  test/system/executable/configurations/simple_configuration.yaml
  test/system/executable/configurations/void_configuration.yaml
  test/unittest/configuration/CMakeLists.txt
  test/unittest/configuration/ConfigurationTest.cpp
  test/unittest/participant/participant_factory/CMakeLists.txt
  test/unittest/participant/participant_factory/ParticipantFactoryTest.cpp
  test/unittest/participant/participants_database/CMakeLists.txt
Labels: to-library

#124 Feature/library/cmake refactor [13546]
  CMakeLists.txt
  cmake/packaging/Config.cmake.in
  cmake/packaging/eProsimaPackaging.cmake
  docs/rst/developer_manual/installation/configuration/cmake_options.rst
  include/ddsrouter/core/DDSRouter.hpp
  include/ddsrouter/library/config.h.in
  include/ddsrouter/library/ddsrouter_dll.h
  include/ddsrouter/library/eProsima_auto_link.h
  src/cpp/CMakeLists.txt
  test/CMakeLists.txt
  test/tool/CMakeLists.txt
  test/tool/application/CMakeLists.txt
  test/tool/application/configurations/simple_configuration.yaml
  test/tool/application/configurations/void_configuration.yaml
  test/tool/application/launcher.ps1
  test/tool/application/tests.py
  tool/CMakeLists.txt
  tool/cpp/application/CMakeLists.txt
  tool/cpp/application/main.cpp
  tool/cpp/application/user_interface/ProcessReturnCode.hpp
  tool/cpp/application/user_interface/arguments_configuration.cpp
  tool/cpp/application/user_interface/arguments_configuration.hpp
Labels: to-library

#126 TlsConfiguration class [13554]
  include/ddsrouter/configuration/DiscoveryServerParticipantConfiguration.hpp
  include/ddsrouter/participant/implementations/rtps/DiscoveryServerParticipant.hpp
  include/ddsrouter/participant/implementations/rtps/impl/DiscoveryServerParticipant.ipp
  include/ddsrouter/security/tls/TlsConfiguration.hpp
  include/ddsrouter/security/tls/TlsConfigurationBoth.hpp
  include/ddsrouter/security/tls/TlsConfigurationClient.hpp
  include/ddsrouter/security/tls/TlsConfigurationServer.hpp
  src/cpp/configuration/DiscoveryServerParticipantConfiguration.cpp
  src/cpp/security/tls/TlsConfiguration.cpp
  src/cpp/security/tls/TlsConfigurationBoth.cpp
  src/cpp/security/tls/TlsConfigurationClient.cpp
  src/cpp/security/tls/TlsConfigurationServer.cpp
  test/blackbox/CMakeLists.txt
  test/unittest/participant/participant_factory/CMakeLists.txt
Labels: to-library
